#!/usr/bin/python3
#Based on aurlist (https://github.com/oshazard/aurlist/)

import sqlite3
import os

dbpath = os.path.expanduser("~/.aurdb.db")

REPOCOLOR='\x1b[1;35m'
PKGCOLOR='\x1b[1;39m'
VERCOLOR='\x1b[1;32m'
FLAGCOLOR='\x1b[1;31m'
RESETCOLOR='\x1b[0m'

con = sqlite3.connect(dbpath)
cur = con.cursor()    

cur.execute("SELECT * FROM packages ORDER BY Name")
for pkg in cur.fetchall():
    d = dict(zip(('Depends', 'Provides', 'Name', 'URL', 'Maintainer', 'URLPath', 'MakeDepends', 'Replaces', 'PackageBaseID', 'OptDepends', 'License', 'OutOfDate', 'FirstSubmitted', 'CategoryID', 'CheckDepends', 'Conflicts', 'Description', 'NumVotes', 'Groups', 'LastModified', 'ID', 'PackageBase', 'Version'), pkg))


    vercolor = VERCOLOR
    if d["OutOfDate"]:
        vercolor = FLAGCOLOR

    print("%saur/%s%s %s%s %s(%d)\n\t%s" % (REPOCOLOR, PKGCOLOR, d["Name"], vercolor, d["Version"], RESETCOLOR, d["NumVotes"], d["Description"]))

con.close()
